Docker container image for Repose Internal
rackerlabs/cloudfeeds-repose-filters pull request #34
Opened 2021-05-05 13:01 UTC by deep8103

- Identity integration tested and working fine.
- TenantId authorization is pending. 
- Tested in a containerized env with a running AtomHopper.

2021-05-05 13:04 UTC, deep8103 commented
It contains the changes of https://github.com/rackerlabs/cloudfeeds-repose-filters/pull/33 but that would not be visible after the merge of this PR.

Only files changed in this PR: 
1. docker/configuration/internal/system-model.cfg.xml 
2. docker/configuration/internal/http-connection-pool.cfg.xml

2021-05-06 19:22 UTC, AJStieren requested changes
Dealing with a hardware failure. Will test once I've got it... mitigated. In the meantime had a tiny request and a question.

2021-05-06 19:22 UTC, AJStieren commented on docker/configuration/internal/http-connection-pool.cfg.xml
> -        http.connection.max-status-line-garbage="100"
Is this config gone in the current filter version or was it just non-functional?

2021-05-06 19:22 UTC, AJStieren commented on docker/configuration/common/keystone-v2.cfg.xml
> +</keystone-v2>
Super mega ultra nitpicking request: Add an empty line at the end of the file.
```suggestion
</keystone-v2>

```

It makes me happy. Also there is a super niche scenario of very specific systems failing to read the last line in files.

2021-05-07 16:44 UTC, deep8103 commented on docker/configuration/internal/http-connection-pool.cfg.xml
> -        http.connection.max-status-line-garbage="100"
Removed in the newer version of Repose.

2021-05-07 16:48 UTC, deep8103 commented on docker/configuration/common/keystone-v2.cfg.xml
> +</keystone-v2>
Done.

2021-05-14 21:12 UTC, AJStieren approved these changes

2021-05-17 08:43 UTC, merged